// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKh_fp7SJSDh70u5IPv-lZtes_D4Mf6V0',
    appId: '1:791118994429:web:aa64f5d6ad9a2bf3f79794',
    messagingSenderId: '791118994429',
    projectId: 'my-notes-47fe5',
    authDomain: 'my-notes-47fe5.firebaseapp.com',
    storageBucket: 'my-notes-47fe5.appspot.com',
    measurementId: 'G-FRR80Y8WBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAp3qISOU9wq0N-617lbWWyRIVUXclrks',
    appId: '1:791118994429:android:ab2ea6562cf89997f79794',
    messagingSenderId: '791118994429',
    projectId: 'my-notes-47fe5',
    storageBucket: 'my-notes-47fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB794gQhNPpl1W18RpAasdrmOtT3iBSFfg',
    appId: '1:791118994429:ios:d8368e4d63d0cfebf79794',
    messagingSenderId: '791118994429',
    projectId: 'my-notes-47fe5',
    storageBucket: 'my-notes-47fe5.appspot.com',
    iosClientId: '791118994429-ukqni5vjhhlfhnrl97kpli9enave0d0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB794gQhNPpl1W18RpAasdrmOtT3iBSFfg',
    appId: '1:791118994429:ios:d8368e4d63d0cfebf79794',
    messagingSenderId: '791118994429',
    projectId: 'my-notes-47fe5',
    storageBucket: 'my-notes-47fe5.appspot.com',
    iosClientId: '791118994429-ukqni5vjhhlfhnrl97kpli9enave0d0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
